import 'package:bus_service/core/models/models.dart';

/// Provides seed/demo data for Surat-to-village routes when Firestore is empty.
class SeedDataService {
  SeedDataService._();

  static const String defaultTenantId = 'T1';

  static List<RouteStop> get suratRouteStops => [
        const RouteStop(
          id: 'S1',
          name: 'Surat Central',
          nameGuj: 'સુરત સેન્ટ્રલ',
          latitude: 21.1702,
          longitude: 72.8311,
          orderIndex: 0,
          isBoardingPoint: true,
        ),
        const RouteStop(
          id: 'S2',
          name: 'Adajan',
          nameGuj: 'અડાજણ',
          latitude: 21.1950,
          longitude: 72.7930,
          orderIndex: 1,
          isBoardingPoint: true,
        ),
        const RouteStop(
          id: 'S3',
          name: 'Varachha',
          nameGuj: 'વરાછા',
          latitude: 21.2147,
          longitude: 72.8777,
          orderIndex: 2,
          isBoardingPoint: true,
        ),
        const RouteStop(
          id: 'S4',
          name: 'Katargam',
          nameGuj: 'કતારગામ',
          latitude: 21.2270,
          longitude: 72.8330,
          orderIndex: 3,
          isBoardingPoint: true,
        ),
        const RouteStop(
          id: 'S5',
          name: 'Udhna',
          nameGuj: 'ઉધના',
          latitude: 21.1620,
          longitude: 72.8500,
          orderIndex: 4,
          isBoardingPoint: true,
        ),
        const RouteStop(
          id: 'S6',
          name: 'Kamrej',
          nameGuj: 'કામરેજ',
          latitude: 21.2700,
          longitude: 72.9600,
          orderIndex: 5,
        ),
        const RouteStop(
          id: 'S7',
          name: 'Bardoli',
          nameGuj: 'બારડોલી',
          latitude: 21.1220,
          longitude: 73.1110,
          orderIndex: 6,
          isDropPoint: true,
        ),
        const RouteStop(
          id: 'S8',
          name: 'Vyara',
          nameGuj: 'વ્યારા',
          latitude: 21.1100,
          longitude: 73.3900,
          orderIndex: 7,
          isDropPoint: true,
        ),
        const RouteStop(
          id: 'S9',
          name: 'Mahuva',
          nameGuj: 'મહુવા',
          latitude: 21.0830,
          longitude: 73.1300,
          orderIndex: 8,
          isDropPoint: true,
        ),
      ];

  static List<RouteStop> get suratRirampurStops => [
        const RouteStop(
          id: 'SR01',
          name: 'Vadla Parking (Katargam, Surat)',
          nameGuj: 'વડલા પાર્કિંગ (કતારગામ, સુરત)',
          latitude: 21.2294,
          longitude: 72.8258,
          orderIndex: 0,
          isBoardingPoint: true,
        ),
        const RouteStop(
          id: 'SR02',
          name: 'Gajera Circle',
          nameGuj: 'ગજેરા સર્કલ',
          latitude: 21.2238,
          longitude: 72.8439,
          orderIndex: 1,
          isBoardingPoint: true,
        ),
        const RouteStop(
          id: 'SR03',
          name: 'Vallabhacharya Marg',
          nameGuj: 'વલ્લભાચાર્ય માર્ગ',
          latitude: 21.2185,
          longitude: 72.8490,
          orderIndex: 2,
          isBoardingPoint: true,
        ),
        const RouteStop(
          id: 'SR04',
          name: 'Hirabaug',
          nameGuj: 'હીરાબાગ',
          latitude: 21.2091,
          longitude: 72.8552,
          orderIndex: 3,
          isBoardingPoint: true,
        ),
        const RouteStop(
          id: 'SR05',
          name: 'Kapodra',
          nameGuj: 'કાપોદ્રા',
          latitude: 21.2064,
          longitude: 72.8645,
          orderIndex: 4,
          isBoardingPoint: true,
        ),
        const RouteStop(
          id: 'SR06',
          name: 'Nana Varachha',
          nameGuj: 'નાના વરાછા',
          latitude: 21.2037,
          longitude: 72.8752,
          orderIndex: 5,
          isBoardingPoint: true,
        ),
        const RouteStop(
          id: 'SR07',
          name: 'Sarthana',
          nameGuj: 'સરથાણા',
          latitude: 21.2215,
          longitude: 72.9015,
          orderIndex: 6,
          isBoardingPoint: true,
        ),
        const RouteStop(
          id: 'SR08',
          name: 'Shyam Dham Mandir',
          nameGuj: 'શ્યામધામ મંદિર',
          latitude: 21.2260,
          longitude: 72.9095,
          orderIndex: 7,
          isBoardingPoint: true,
        ),
        const RouteStop(
          id: 'SR09',
          name: 'Sagvadi',
          nameGuj: 'સાગવાડી',
          latitude: 21.2330,
          longitude: 72.9165,
          orderIndex: 8,
          isBoardingPoint: true,
        ),
        const RouteStop(
          id: 'SR10',
          name: 'Valak Patiya',
          nameGuj: 'વલાક પાટિયા',
          latitude: 21.2410,
          longitude: 72.9230,
          orderIndex: 9,
          isBoardingPoint: true,
        ),
        const RouteStop(
          id: 'SR11',
          name: 'Laskana',
          nameGuj: 'લસકાણા',
          latitude: 21.2505,
          longitude: 72.9325,
          orderIndex: 10,
          isBoardingPoint: true,
        ),
        const RouteStop(
          id: 'SR12',
          name: 'Diamond Nagar',
          nameGuj: 'ડાયમંડ નગર',
          latitude: 21.2555,
          longitude: 72.9385,
          orderIndex: 11,
          isBoardingPoint: true,
        ),
        const RouteStop(
          id: 'SR13',
          name: 'Pasodra Patiya',
          nameGuj: 'પાસોદરા પાટિયા',
          latitude: 21.2615,
          longitude: 72.9460,
          orderIndex: 12,
          isBoardingPoint: true,
        ),
        const RouteStop(
          id: 'SR14',
          name: 'Kamrej',
          nameGuj: 'કામરેજ',
          latitude: 21.2687,
          longitude: 72.9648,
          orderIndex: 13,
          isBoardingPoint: true,
        ),
        const RouteStop(
          id: 'SR15',
          name: 'Bharuch',
          nameGuj: 'ભરૂચ',
          latitude: 21.7247,
          longitude: 73.0189,
          orderIndex: 14,
          isDropPoint: true,
        ),
        const RouteStop(
          id: 'SR16',
          name: 'Vadodara',
          nameGuj: 'વડોદરા',
          latitude: 22.3072,
          longitude: 73.1812,
          orderIndex: 15,
          isDropPoint: true,
        ),
        const RouteStop(
          id: 'SR17',
          name: 'Tarapur',
          nameGuj: 'તારાપુર',
          latitude: 22.4831,
          longitude: 72.6586,
          orderIndex: 16,
          isDropPoint: true,
        ),
        const RouteStop(
          id: 'SR18',
          name: 'Vataman',
          nameGuj: 'વાટામણ',
          latitude: 22.4285,
          longitude: 72.5194,
          orderIndex: 17,
          isDropPoint: true,
        ),
        const RouteStop(
          id: 'SR19',
          name: 'Bagodra',
          nameGuj: 'બગોદરા',
          latitude: 22.3789,
          longitude: 72.2611,
          orderIndex: 18,
          isDropPoint: true,
        ),
        const RouteStop(
          id: 'SR20',
          name: 'Dhandhuka',
          nameGuj: 'ધંધુકા',
          latitude: 22.3688,
          longitude: 71.9845,
          orderIndex: 19,
          isDropPoint: true,
        ),
        const RouteStop(
          id: 'SR21',
          name: 'Pipli',
          nameGuj: 'પીપળી',
          latitude: 22.3551,
          longitude: 71.8624,
          orderIndex: 20,
          isDropPoint: true,
        ),
        const RouteStop(
          id: 'SR22',
          name: 'Atkot',
          nameGuj: 'આટકોટ',
          latitude: 22.0012,
          longitude: 71.1895,
          orderIndex: 21,
          isDropPoint: true,
        ),
        const RouteStop(
          id: 'SR23',
          name: 'Babra',
          nameGuj: 'બાબરા',
          latitude: 21.8494,
          longitude: 71.3039,
          orderIndex: 22,
          isDropPoint: true,
        ),
        const RouteStop(
          id: 'SR24',
          name: 'Vavdi',
          nameGuj: 'વાવડી',
          latitude: 21.8021,
          longitude: 71.2115,
          orderIndex: 23,
          isDropPoint: true,
        ),
        const RouteStop(
          id: 'SR25',
          name: 'Mota Devaliya',
          nameGuj: 'મોટા દેવળીયા',
          latitude: 21.7612,
          longitude: 71.1215,
          orderIndex: 24,
          isDropPoint: true,
        ),
        const RouteStop(
          id: 'SR26',
          name: 'Rirampur',
          nameGuj: 'રામપુર',
          latitude: 21.7015,
          longitude: 71.0152,
          orderIndex: 25,
          isDropPoint: true,
        ),
      ];

  static BusRoute get suratRirampurRoute => BusRoute(
        id: 'SURAT_RIRAMPUR',
        tenantId: defaultTenantId,
        name: 'Surat - Rirampur Express',
        origin: 'Surat',
        destination: 'Rirampur',
        stops: suratRirampurStops,
      );

  static BusRoute get suratBardoliRoute => BusRoute(
        id: 'RT001',
        tenantId: defaultTenantId,
        name: 'Surat - Bardoli - Vyara',
        origin: 'Surat',
        destination: 'Vyara',
        stops: suratRouteStops,
      );

  static List<Bus> get defaultBuses => [
        Bus(
          id: 'B1',
          busNumber: 'GJ-05-AB-1234',
          tenantId: defaultTenantId,
          totalSeats: 36,
          layoutType: BusLayoutType.sleeper,
          exteriorPhotoUrl:
              'https://images.unsplash.com/photo-1544620305-c4d4b122a993?w=800',
          interiorPhotoUrl:
              'https://images.unsplash.com/photo-1570125909232-e097763bc976?w=800',
          berthPhotoUrls: [
            'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800',
            'https://images.unsplash.com/photo-1544620305-c4d4b122a993?w=800',
          ],
        ),
        Bus(
          id: 'B2',
          busNumber: 'GJ-05-CD-5678',
          tenantId: defaultTenantId,
          totalSeats: 40,
          layoutType: BusLayoutType.sleeper,
          exteriorPhotoUrl:
              'https://images.unsplash.com/photo-1570125909232-e097763bc976?w=800',
          interiorPhotoUrl:
              'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800',
          berthPhotoUrls: [
            'https://images.unsplash.com/photo-1544620305-c4d4b122a993?w=800',
          ],
        ),
      ];

  static List<UserStaff> get defaultStaff => [
        const UserStaff(
          uid: 'D101',
          name: 'Rajesh Kumar',
          phone: '+919876543210',
          role: UserRole.driver,
          tenantId: defaultTenantId,
        ),
        const UserStaff(
          uid: 'C201',
          name: 'Amit Sharma',
          phone: '+919876543109',
          role: UserRole.conductor,
          tenantId: defaultTenantId,
        ),
        const UserStaff(
          uid: 'D102',
          name: 'Suresh Patel',
          phone: '+919876543108',
          role: UserRole.driver,
          tenantId: defaultTenantId,
        ),
        const UserStaff(
          uid: 'C202',
          name: 'Kiran Desai',
          phone: '+919876543107',
          role: UserRole.conductor,
          tenantId: defaultTenantId,
        ),
      ];

  static List<Trip> get defaultTrips => [
        Trip(
          id: 'TR001',
          tenantId: defaultTenantId,
          busId: 'B1',
          driverId: 'D101',
          conductorId: 'C201',
          routeId: 'RT001',
          status: TripStatus.live,
          startDateTime: DateTime.now(),
        ),
        Trip(
          id: 'TR002',
          tenantId: defaultTenantId,
          busId: 'B2',
          driverId: 'D102',
          conductorId: 'C202',
          routeId: 'RT001',
          status: TripStatus.scheduled,
          startDateTime: DateTime.now().add(const Duration(hours: 4)),
        ),
      ];

  static List<String> get boardingPoints =>
      suratRouteStops.where((s) => s.isBoardingPoint).map((s) => s.nameGuj).toList();

  static List<String> get dropPoints =>
      suratRouteStops.where((s) => s.isDropPoint).map((s) => s.nameGuj).toList();
}
